# Generated by Django 3.2.20 on 2023-10-24 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_student', models.IntegerField()),
                ('id_task', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('input', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Решено'), (1, 'Ошибка'), (2, 'Не приступал')], default=2)),
            ],
            options={
                'db_table': 'Solutions',
            },
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Themes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('difficulty', models.IntegerField(choices=[(0, 'Легко'), (1, 'Медиум'), (2, 'Сложно'), (3, 'Очень сложно')])),
                ('id_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='loginpage.themes')),
                ('solutions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='loginpage.solutions')),
            ],
            options={
                'db_table': 'Tasks',
                'ordering': ['difficulty', 'name'],
            },
        ),
    ]
