# Generated by Django 3.2.20 on 2023-10-24 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0003_auto_20231025_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='solutions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='solutions',
        ),
        migrations.AddField(
            model_name='solutions',
            name='tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Solutions', to='loginpage.tasks'),
        ),
        migrations.AddField(
            model_name='solutions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Solutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='themes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
