# Generated by Django 3.2.20 on 2023-11-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0005_tasks_benchmark_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutions',
            name='id_student',
        ),
        migrations.RemoveField(
            model_name='solutions',
            name='id_task',
        ),
    ]
