# Generated by Django 3.2.20 on 2023-11-21 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0006_auto_20231121_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='tasks',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Solutions', to='loginpage.tasks'),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Solutions', to=settings.AUTH_USER_MODEL),
        ),
    ]
