# Generated by Django 3.2.20 on 2023-11-26 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0011_alter_tasks_benchmark_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='loginpage.groups'),
        ),
    ]
