# Generated by Django 3.2.20 on 2023-11-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0012_user_id_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='in_rating',
            field=models.BooleanField(default=True),
        ),
    ]
